# Generated by Django 4.2.7 on 2023-12-05 08:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='jkccejtc06k0elzgia0m', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Author', models.CharField(default='Anonymous', max_length=100)),
                ('Duration', models.DurationField()),
                ('Rating', models.IntegerField(default=0)),
                ('Price', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Free', 'Free'), ('Subscription', 'Subscription'), ('Paid, & Free', 'Paid, & Free'), ('Free, & Subscription', 'Free, & Subscription'), ('Paid, & Subscription', 'Paid, & Subscription'), ('Paid, Free, & Subscription', 'Paid, Free, & Subscription')], max_length=50, null=True)),
                ('type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Major', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldTitle', models.CharField(max_length=255)),
                ('FieldDescription', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='jkccejtc06k0elzgia0m', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(default='No link available, please report thankn you')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paths.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paths.coursemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paths.fieldmodel'),
        ),
    ]
