# Generated by Django 4.2.7 on 2023-12-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='duration',
            field=models.DurationField(),
            preserve_default=False,
        ),
    ]
