# Generated by Django 4.2.7 on 2023-11-29 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmodel',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='fieldmodel',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='fieldmodel',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='fieldmodel',
            name='Rating',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
