# Generated by Django 4.2.7 on 2023-12-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_lessonmodel_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='lessonmodel',
            name='duration',
        ),
    ]
