# Generated by Django 4.2.7 on 2023-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_remove_coursemodel_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='link',
            field=models.URLField(default='No link available, please report thankn you'),
        ),
        migrations.DeleteModel(
            name='LessonModel',
        ),
    ]
