# Generated by Django 4.2.7 on 2023-11-11 00:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_coursemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldTitle', models.CharField(max_length=255)),
                ('FieldDescription', models.TextField()),
                ('Author', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Rating', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', cloudinary.models.CloudinaryField(default='jkccejtc06k0elzgia0m', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
    ]
