# Generated by Django 4.2.7 on 2023-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_lessonmodel_link_alter_feedbackmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='type',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
