# Generated by Django 4.2.7 on 2023-11-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_coursemodel_lessonmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='image',
        ),
    ]
