# Generated by Django 4.2.7 on 2023-12-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_coursemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='created_at',
        ),
    ]
