# Generated by Django 4.2.7 on 2023-12-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_coursemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='type',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Major', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
