# Generated by Django 4.2.7 on 2023-12-05 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_remove_coursemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
