# Generated by Django 4.2.7 on 2023-12-03 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_alter_coursemodel_type_alter_feedbackmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
