# Generated by Django 4.2.7 on 2023-12-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0010_rename_bookmarks_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
