# Generated by Django 4.2.7 on 2023-12-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0011_delete_bookmark'),
        ('paths', '0011_lessonmodel_delete_bookmark'),
    ]

    operations = [
    ]
