# Generated by Django 4.2.7 on 2023-11-07 22:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_coursemodel_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='taHack\\static\\images\\PLACEHOLDER_NULL.png', max_length=255, verbose_name='image'),
        ),
    ]
